# filesize.py
import os
import time

MAX_LOG_SIZE_MB = 60  # Maximum file size in megabytes

TRC_HEADER_TEMPLATE = (
    ";$FILEVERSION=1.1\n"
    ";$STARTTIME={epoch_days_fraction:.10f}\n"
    ";\n"
    ";   Start time: {human_time}.{millis}.0\n"
    ";   Generated by PCAN-View v5.0.1.007\n"
    ";\n"
    ";   Message Number\n"
    ";   |         Time Offset (ms)\n"
    ";   |         |        Type\n"
    ";   |         |        |        ID (hex)\n"
    ";   |         |        |        |     Data Length\n"
    ";   |         |        |        |     |   Data Bytes (hex) ...\n"
    ";   |         |        |        |     |   |\n"
    ";---+--   ----+----  --+--  ----+---  +  -+ -- -- -- -- -- -- --\n"
)


class LogFileHandler:
    def __init__(self, base_filename):
        self.base_filename = base_filename
        self.max_size = MAX_LOG_SIZE_MB * 1024 * 1024
        self.file_index = 1
        self.log_file = None
        self.start_new_file(first_file=True)

    def start_new_file(self, first_file=False):
        """Close current log file (if any) and start a new one.
        Write header only for files after the first.
        """
        if self.log_file:
            self.log_file.close()

        base, ext = os.path.splitext(self.base_filename)
        filename = f"{base}_{self.file_index}{ext}"
        self.log_file = open(filename, "w", encoding="utf-8")

        if not first_file:  # Header only for 2nd file onwards
            dt_now = time.localtime()
            human_time = time.strftime("%d-%m-%Y %H:%M:%S", dt_now)
            millis = int((time.time() % 1) * 1000)
            epoch_days_fraction = time.time() / 86400

            self.log_file.write(TRC_HEADER_TEMPLATE.format(
                epoch_days_fraction=epoch_days_fraction,
                human_time=human_time,
                millis=millis
            ))
            self.log_file.flush()

        self.file_index += 1
        return filename

    def write(self, data_line):
        """Write data to current log file and rotate if size exceeds limit."""
        if not self.log_file:
            self.start_new_file()

        self.log_file.write(data_line)
        self.log_file.flush()

        if os.path.getsize(self.log_file.name) >= self.max_size:
            # Create next file with header (since it's not first anymore)
            self.start_new_file(first_file=False)

    def close(self):
        """Close the current log file if open."""
        if self.log_file:
            self.log_file.close()
            self.log_file = None
